[project]
authors = [
    {name = "Jani Sourander", email = "sourander@gmail.com"},
]
requires-python = "<4.0,>=3.10"
dependencies = [
    "mkdocs-material~=9.5",
    "mkdocs-awesome-pages-plugin~=2.9",
]
name = "doc-skeleton"
version = "0.1.0"
description = ""
readme = "README.md"
